"""Add is_active to Post

Revision ID: 6fa61d036613
Revises: 143ce9d1e084
Create Date: 2024-11-26 23:07:22.936385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa61d036613'
down_revision = '143ce9d1e084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('author')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
