"""Add about_me and last_seen fields to User model

Revision ID: 6faa1afd6a60
Revises: 757a8ec6ed96
Create Date: 2024-12-14 14:24:54.819828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6faa1afd6a60'
down_revision = '757a8ec6ed96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
