"""Add topic and announcement models

Revision ID: 9255062a7251
Revises: 999ffc7ddc55
Create Date: 2024-12-15 21:13:20.717233

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '9255062a7251'
down_revision = '999ffc7ddc55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_topics',
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('announcement_id', 'topic_id')
    )
   
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('announcement_tags')
    op.drop_table('announcements')
    # ### end Alembic commands ###
