"""Add tag and announcement models

Revision ID: 999ffc7ddc55
Revises: 0c636cc64c7c
Create Date: 2024-12-14 22:19:14.581555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999ffc7ddc55'
down_revision = '0c636cc64c7c'
branch_labels = None
depends_on = None

from sqlalchemy import inspect


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('announcement_tags',
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('announcement_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = inspect(op.get_bind())
    
    if 'announcement_topics' in inspector.get_table_names():
        op.drop_table('announcement_topics')
    # ### end Alembic commands ###
