"""adding user_id to announcements

Revision ID: a33a7adc249a
Revises: 9255062a7251
Create Date: 2024-12-16 13:52:37.630830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33a7adc249a'
down_revision = '9255062a7251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_announcements_user_id', 'users', ['user_id'], ['id'])
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM users LIMIT 1"))
    default_user_id = result.scalar() or 1
    connection.execute(
        sa.text("UPDATE announcements SET user_id = :user_id").bindparams(user_id=default_user_id)
    )

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
