"""update author in db

Revision ID: d233101abed0
Revises: c6eef5444ca6
Create Date: 2024-11-26 23:56:30.976645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd233101abed0'
down_revision = 'c6eef5444ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('posted',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('posted',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
